name: Test node.ext.ldap

on:
  push:

jobs:
  test:
    name: Test ${{ matrix.python }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

        python:
          - "2.7"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install system dependencies
        run: make system-dependencies

      - name: Install project
        run: PYTHON=python make install

      - name: Run tests an collect code coverage
        run: make coverage
