name: Tests

on: [push]

jobs:
  test:
    name: Test ${{ matrix.python }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

        python:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install system dependencies
        run: make system-dependencies

      - name: Install project
        run: make install

      - name: Run tests an collect code coverage
        run: make coverage
